# - Find PROSILICA
# Find the native PROSILICA includes and library
# This module defines
#  PROSILICA_INCLUDE_DIR, where to find jpeglib.h, etc.
#  PROSILICA_LIBRARIES, the libraries needed to use PROSILICA.
#  PROSILICA_FOUND, If false, do not try to use PROSILICA.
# also defined, but not for general use are
#  PROSILICA_LIBRARY, where to find the PROSILICA library.

FIND_PATH(PROSILICA_INCLUDE_DIR PvApi.h PATHS /usr/local/include /usr/include)

SET(PROSILICA_NAMES ${PROSILICA_NAMES} PvAPI pthread rt)
FIND_LIBRARY(PROSILICA_LIBRARY_PVAPI
  NAMES PvAPI
  PATHS /usr/lib /usr/local/lib /usr/lib64 /usr/local/lib64
)
FIND_LIBRARY(PROSILICA_LIBRARY_PTHREAD
  NAMES pthread
  PATHS /usr/lib /usr/local/lib /usr/lib64 /usr/local/lib64
)
FIND_LIBRARY(PROSILICA_LIBRARY_RT
  NAMES rt
  PATHS /usr/lib /usr/local/lib /usr/lib64 /usr/local/lib64
)

IF (PROSILICA_LIBRARY_PVAPI AND PROSILICA_LIBRARY_PTHREAD AND PROSILICA_LIBRARY_RT AND PROSILICA_INCLUDE_DIR)
  SET(PROSILICA_LIBRARIES ${PROSILICA_LIBRARIES} ${PROSILICA_LIBRARY_PVAPI})
  SET(PROSILICA_LIBRARIES ${PROSILICA_LIBRARIES} ${PROSILICA_LIBRARY_PTHREAD})
  SET(PROSILICA_LIBRARIES ${PROSILICA_LIBRARIES} ${PROSILICA_LIBRARY_RT})
  SET(PROSILICA_FOUND "YES")
ELSE (PROSILICA_LIBRARY_PVAPI AND PROSILICA_LIBRARY_PTHREAD AND PROSILICA_LIBRARY_RT AND PROSILICA_INCLUDE_DIR)
  SET(PROSILICA_FOUND "NO")
ENDIF (PROSILICA_LIBRARY_PVAPI AND PROSILICA_LIBRARY_PTHREAD AND PROSILICA_LIBRARY_RT AND PROSILICA_INCLUDE_DIR)


IF (PROSILICA_FOUND)
   IF (NOT PROSILICA_FIND_QUIETLY)
      MESSAGE(STATUS "Found PROSILICA: ${PROSILICA_LIBRARIES}")
   ENDIF (NOT PROSILICA_FIND_QUIETLY)
ELSE (PROSILICA_FOUND)
   IF (PROSILICA_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find PROSILICA library")
   ENDIF (PROSILICA_FIND_REQUIRED)
ENDIF (PROSILICA_FOUND)

# Deprecated declarations.
SET (NATIVE_PROSILICA_INCLUDE_PATH ${PROSILICA_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_PROSILICA_LIB_PATH ${PROSILICA_LIBRARY_PVAPI} PATH)

MARK_AS_ADVANCED(
  PROSILICA_LIBRARY_PVAPI
  PROSILICA_LIBRARY_PTHREAD
  PROSILICA_LIBRARY_RT
  PROSILICA_INCLUDE_DIR
  )

