# - Find EPIPHAN
# Find the native EPIPHAN includes and library
# This module defines
#  EPIPHAN_INCLUDE_DIR, where to find pt.h, etc.
#  EPIPHAN_LIBRARIES, the libraries needed to use EPIPHAN.
#  EPIPHAN_FOUND, If false, do not try to use EPIPHAN.
# also defined, but not for general use are
#  EPIPHAN_LIBRARY, where to find the EPIPHAN library.

FIND_PATH(EPIPHAN_INCLUDE_DIR frmgrab.h
/usr/local/include
/usr/include
)

SET(EPIPHAN_NAMES ${EPIPHAN_NAMES} frmgrab)
FIND_LIBRARY(EPIPHAN_LIBRARY
  NAMES ${EPIPHAN_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

IF (EPIPHAN_LIBRARY AND EPIPHAN_INCLUDE_DIR)
    SET(EPIPHAN_LIBRARIES ${EPIPHAN_LIBRARY})
    SET(EPIPHAN_FOUND "YES")
ELSE (EPIPHAN_LIBRARY AND EPIPHAN_INCLUDE_DIR)
  SET(EPIPHAN_FOUND "NO")
ENDIF (EPIPHAN_LIBRARY AND EPIPHAN_INCLUDE_DIR)


IF (EPIPHAN_FOUND)
   IF (NOT EPIPHAN_FIND_QUIETLY)
      MESSAGE(STATUS "Found EPIPHAN: ${EPIPHAN_LIBRARIES}")
   ENDIF (NOT EPIPHAN_FIND_QUIETLY)
ELSE (EPIPHAN_FOUND)
   IF (EPIPHAN_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find EPIPHAN library")
   ENDIF (EPIPHAN_FIND_REQUIRED)
ENDIF (EPIPHAN_FOUND)

# Deprecated declarations.
SET (NATIVE_EPIPHAN_INCLUDE_PATH ${EPIPHAN_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_EPIPHAN_LIB_PATH ${EPIPHAN_LIBRARY} PATH)

MARK_AS_ADVANCED(
  EPIPHAN_LIBRARY
  EPIPHAN_INCLUDE_DIR
)

