# - Find BLACKMAGIC
# Find the native BLACKMAGIC includes and library
# This module defines
#  BLACKMAGIC_INCLUDE_DIR, where to find pt.h, etc.
#  BLACKMAGIC_LIBRARIES, the libraries needed to use BLACKMAGIC.
#  BLACKMAGIC_FOUND, If false, do not try to use BLACKMAGIC.
# also defined, but not for general use are
#  BLACKMAGIC_LIBRARY, where to find the BLACKMAGIC library.

FIND_PATH(BLACKMAGIC_INCLUDE_DIR DeckLinkAPI.h
/usr/local/include
/usr/include
)

SET(BLACKMAGIC_NAMES ${BLACKMAGIC_NAMES} decklink)

FIND_LIBRARY(BLACKMAGIC_LIBRARY
  NAMES ${BLACKMAGIC_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

IF (BLACKMAGIC_LIBRARY AND BLACKMAGIC_INCLUDE_DIR)
    SET(BLACKMAGIC_LIBRARIES ${BLACKMAGIC_LIBRARY})
    SET(BLACKMAGIC_FOUND "YES")
ELSE (BLACKMAGIC_LIBRARY AND BLACKMAGIC_INCLUDE_DIR)
    SET(BLACKMAGIC_FOUND "NO")
ENDIF (BLACKMAGIC_LIBRARY AND BLACKMAGIC_INCLUDE_DIR)


IF (BLACKMAGIC_FOUND)
   IF (NOT BLACKMAGIC_FIND_QUIETLY)
      MESSAGE(STATUS "Found BLACKMAGIC: ${BLACKMAGIC_LIBRARIES}")
   ENDIF (NOT BLACKMAGIC_FIND_QUIETLY)
ELSE (BLACKMAGIC_FOUND)
   IF (BLACKMAGIC_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find BLACKMAGIC library")
   ENDIF (BLACKMAGIC_FIND_REQUIRED)
ENDIF (BLACKMAGIC_FOUND)

# Deprecated declarations.
SET (NATIVE_BLACKMAGIC_INCLUDE_PATH ${BLACKMAGIC_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_BLACKMAGIC_LIB_PATH ${BLACKMAGIC_LIBRARY} PATH)

MARK_AS_ADVANCED(
  BLACKMAGIC_LIBRARIES
  BLACKMAGIC_INCLUDE_DIR
)

