# - Find PROFILOMETRE
# Find the native PROFILOMETRE includes and library
# This module defines
#  PROFILOMETRE_INCLUDE_DIR, where to find jpeglib.h, etc.
#  PROFILOMETRE_LIBRARIES, the libraries needed to use PROFILOMETRE.
#  PROFILOMETRE_FOUND, If false, do not try to use PROFILOMETRE.
# also defined, but not for general use are
#  PROFILOMETRE_LIBRARY, where to find the PROFILOMETRE library.

FIND_PATH(PROFILOMETRE_INCLUDE_DIR profilometre.h PATHS /usr/local/include /usr/include)

FIND_LIBRARY(PROFILOMETRE_LIBRARY
  NAMES profilometre
  PATHS /usr/local/lib /usr/lib
  )

IF (PROFILOMETRE_LIBRARY AND PROFILOMETRE_INCLUDE_DIR)
    SET(PROFILOMETRE_LIBRARIES ${PROFILOMETRE_LIBRARY})
    SET(PROFILOMETRE_FOUND "YES")
ELSE (PROFILOMETRE_LIBRARY AND PROFILOMETRE_INCLUDE_DIR)
  SET(PROFILOMETRE_FOUND "NO")
ENDIF (PROFILOMETRE_LIBRARY AND PROFILOMETRE_INCLUDE_DIR)


IF (PROFILOMETRE_FOUND)
   IF (NOT PROFILOMETRE_FIND_QUIETLY)
      MESSAGE(STATUS "Found PROFILOMETRE: ${PROFILOMETRE_LIBRARIES}")
   ENDIF (NOT PROFILOMETRE_FIND_QUIETLY)
ELSE (PROFILOMETRE_FOUND)
   IF (PROFILOMETRE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find PROFILOMETRE library")
   ENDIF (PROFILOMETRE_FIND_REQUIRED)
ENDIF (PROFILOMETRE_FOUND)

# Deprecated declarations.
SET (NATIVE_PROFILOMETRE_INCLUDE_PATH ${PROFILOMETRE_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_PROFILOMETRE_LIB_PATH ${PROFILOMETRE_LIBRARY} PATH)

MARK_AS_ADVANCED(
  PROFILOMETRE_LIBRARY
  PROFILOMETRE_INCLUDE_DIR
  )

